# .scrutinizer.yml
checks:
  php: true
build:
  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run
  environment:
    docker: true
    redis: false
    php:
      version: 8.0
      pecl_extensions:
        - igbinary
        - redis
  tests:
    override:
      - 'docker run -p 6379:6379 --name redis-redisgraph redislabs/redisgraph:latest'
      -
        command: 'composer run unit-tests'
        coverage:
          file: 'tests/_output/coverage.xml'
          format: 'clover'
filter:
  excluded_paths:
    - "tests/"